### ISSUE TITLE
UINavigationController -> setViewControllers

### ISSUE THREAD

**Issue by tarokker** [grav/leakdetect#2]
Great class!!
Any chance to support also setViewControllers from UINavigationController? :)

**Comment by grav** [comment]
@tarokker sorry for the late answer. <del>Just tried it with `setViewControllers`, and when I press Back, a leak is correctly detected, since the check is done in `popViewControllerAnimated:`.</del>

<del>Closing for now. Can you come up with an example using `setViewControllers` where a leak isn't detected?</del>

Edit: silly me, I see what you mean :-) I'll see if it's possible to detect.

**Comment by grav** [comment]
I've pushed an update, v0.2.2, which also tests all View Controllers that are being replaced when `setViewControllers:` are called. Should be on CocoaPods now.

**Comment by tarokker** [comment]
wow, so fast!
thank you!!
